remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
color-scheme: dark
platforms: false
favicon: true
title: Homepage of Lucas Piessevaux
navigation:
  - name: Home
    link: ./index.html
 - name: Teaching
    link: ./teaching.html
  - name: Notes
    link: ./notes.html
  - name: Research
    link: ./research.html
  - name: Contact
    link: ./contact.html
  - name: Music
    link: ./music.html
